EXP-2 trigger failure

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,25 +1,55 @@
-name: CI Pipeline
+# name: CI Pipeline
+
+# on:
+#   pull_request:
+#   push:
+#     branches: [main]
+
+# jobs:
+#   build-and-test:
+#     runs-on: ubuntu-latest
+
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v4
+
+#       - name: Setup Node
+#         uses: actions/setup-node@v4
+#         with:
+#           node-version: 18
+
+#       - name: Install dependencies
+#         run: npm install
+
+#       - name: Run tests
+#         run: npm test
+
+
+
+
+name: Tests
 
 on:
-  pull_request:
   push:
-    branches: [main]
+    branches:
+      - develop
+      - feature/*
 
 jobs:
-  build-and-test:
+  test:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Setup Node
-        uses: actions/setup-node@v4
-        with:
-          node-version: 18
-
-      - name: Install dependencies
-        run: npm install
+      - uses: actions/checkout@v4
 
       - name: Run tests
-        run: npm test
+        run: |
+          echo "Running tests for $GITHUB_REF_NAME"
+
+          # Fail only for EXP-2 branch
+          if [[ "$GITHUB_REF_NAME" == "feature/EXP-2-checkout-freeze" ]]; then
+            echo "Checkout tests failed"
+            exit 1
+          fi
+
+          echo "All tests passed"
